# Generated by Django 4.1.7 on 2023-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('complited', models.BooleanField()),
            ],
        ),
    ]
